### ISSUE TITLE
Add lightbox-exporter scrape config to prometheus on the management server

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-roles#287]
Sample scrape config:

```yaml

- job_name: 'lightbox-exporter'
  metrics_path: /metrics
  scrape_timeout: 25s
  scrape_interval: 30s
  honor_timestamps: True
  static_configs:
  - targets:
    - storage-0:8090
    - storage-1:8090
    - storage-2:8090

  params:
    collect[]:
    - clustering
    - datapath
    - duroslight
    - meminfo
    - textfile
    - lightfield
    - netstat
    - netdev
    - cpufreq

- job_name: lightos-smart
  scheme: http
  scrape_timeout: 10s
  scrape_interval: 5m
  metrics_path: /metrics
  honor_timestamps: True
  params:
    collect[]:
    - smart
  static_configs:
  - targets:
    - storage-0:8090
    - storage-1:8090
    - storage-2:8090



```
