### ISSUE TITLE
rethinkdb-back-restore relies on `environment_name`

### ISSUE THREAD

**Issue by suckowbiz** [metal-stack/metal-roles#3]
Expectation:
When all mandatory variables are set a successful deployment is expected.

Experienced behavior:
Ansible fails to deploy with following issue:

```
deploy-api  | TASK [metal-roles/control-plane/roles/rethinkdb-backup-restore : Check mandatory variables for this role are set] ***
deploy-api  | task path: /root/.ansible/roles/metal-roles/control-plane/roles/rethinkdb-backup-restore/tasks/main.yml:2
deploy-api  | ok: [localhost] => changed=false 
deploy-api  |   msg: All assertions passed
deploy-api  | 
deploy-api  | TASK [metal-roles/control-plane/roles/rethinkdb-backup-restore : Deploy rethinkdb (backup-restore)] ***
deploy-api  | task path: /root/.ansible/roles/metal-roles/control-plane/roles/rethinkdb-backup-restore/tasks/main.yml:9
deploy-api  | fatal: [localhost]: FAILED! => 
deploy-api  |   msg: |-
deploy-api  |     The task includes an option with an undefined variable. The error was: 'environment_name' is undefined
deploy-api  |   
deploy-api  |     The error appears to be in '/root/.ansible/roles/metal-roles/control-plane/roles/rethinkdb-backup-restore/tasks/main.yml': line 9, column 3, but may
deploy-api  |     be elsewhere in the file depending on the exact syntax problem.
deploy-api  |   
deploy-api  |     The offending line appears to be:
deploy-api  |   
deploy-api  |   
deploy-api  |     - name: Deploy rethinkdb (backup-restore)
deploy-api  |       ^ here
deploy-api  | 
deploy-api  | PLAY RECAP *********************************************************************
deploy-api  | localhost                  : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
deploy-api  | 
deploy-api exited with code 2
```

```
$: ~/go/src/github.com/metal-stack/metal-roles/control-plane/roles/rethinkdb-backup-restore (master=)$ git grep environment_name
templates/rethinkdb.yaml:    object-prefix: rethinkdb-{{ environment_name }}
```

Playbook executed:
```
---
- name: deploy api
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - name: ansible-common
      tags: always
    - name: ingress-controller
      tags: ingress-controller
    - name: metal-roles/control-plane/roles/prepare
      tags: prepare
    - name: metal-roles/control-plane/roles/nsq
      tags: nsq
    - name: metal-roles/control-plane/roles/metal-db
      tags: metal-db
    - name: metal-roles/control-plane/roles/ipam-db
      tags: ipam-db
    - name: metal-roles/control-plane/roles/masterdata-db
      tags: masterdata-db
    - name: metal-roles/control-plane/roles/metal
      tags: metal
```

Workaround:
Set variable `environment_name`
